# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app01', '0003_auto_20171107_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AddField(
            model_name='staff',
            name='auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='账户'),
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(max_length=32, null=True, verbose_name='用户名'),
        ),
    ]
